import requests, bs4, os
os.chdir('D:\\untitled')
exampleFile = open('example.html')
exampleSoup =bs4.BeautifulSoup(exampleFile.read(),"lxml")
elems =exampleSoup.select('#author')
print(type(elems))
print(len(elems))
print(type(elems[0]))
print(elems[0].getText())
print(str(elems[0]))
print(elems[0].attrs)
print('\n')
pElems = exampleSoup.select('p')
print(str(pElems[0]))
print(pElems[0].getText())
print(str(pElems[1]))
print(pElems[1].getText())
print(str(pElems[2]))
print(pElems[2].getText())
print('\n')
spanElem = exampleSoup.select('span')[0]
print(str(spanElem))
print(spanElem.get('id'))
print(spanElem.attrs)
